### ISSUE TITLE
[Bug Report] Jmusic-0.4.0 jar file - a java exception has occured

### ISSUE THREAD

**Issue by itsCrummy** [jagrosh/MusicBot#1497]
### Bug Description

 - a java exception has occured when clicking the 0.4.0 file 

### Steps to Reproduce

download the latest, then attempt to run it after setting up the file

### Expected Result

to load up the music bot

### Debug Output

cannot get bot to load - just has a the following thing in the image below
![image](https://github.com/jagrosh/MusicBot/assets/96262903/c28c0e76-d6c0-4d77-a1ab-3e02bb1c8fa2)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by siggijarl** [comment]
same here

**Comment by MichailiK** [comment]
I believe this is because we have upgraded to Java 11 in version 0.4.0 & you're using Java 8 at the moment. Can you check if you have Java 8 & if you do, upgrade to 11?

**Comment by siggijarl** [comment]
seems to work with AdoptOpenJDK x64 11 which can be handily installed via ninite dot com

**Comment by itsCrummy** [comment]
> I believe this is because we have upgraded to Java 11 in version 0.4.0 & you're using Java 8 at the moment. Can you check if you have Java 8 & if you do, upgrade to 11?

that was the reason why - its fixed now thanks

**Comment by GenFangirl** [comment]
Can you expand on how to update Java?  I downloaded version 11 (11.0.22) and confirmed it is the version I am using by typing java -version into the cmd, but I am still getting the error when trying to run the bot.

**Comment by jagrosh** [comment]
With just that screenshot it's a bit hard to debug. For anyone still running into this issue, can you share the output of running both `java -version` and `java -jar JMusicBot-0.4.0.jar` on the command line

**Comment by GenFangirl** [comment]
Not sure how helpful this is, but here is my output:
![CMDOutputMusicBot](https://github.com/jagrosh/MusicBot/assets/38627254/ae3ed414-78ea-419c-b42e-c3914ba500ee)

**Comment by jagrosh** [comment]
Can you navigate to the folder (`cd ..` to move up a directory, `cd directoryname` to move into a directory) that contains the jar; that particular error is just saying that the jar isn't in the folder you're running the command from

**Comment by GenFangirl** [comment]
Okay, got this 
![image](https://github.com/jagrosh/MusicBot/assets/38627254/791401f2-1767-4391-9388-654d81a2b04c)

**Comment by GenFangirl** [comment]
Okay, got this 
![image](https://github.com/jagrosh/MusicBot/assets/38627254/f0578d61-e9a6-4ea3-ae68-c78bb5b4c0e4)
![image](https://github.com/jagrosh/MusicBot/assets/38627254/9c608a8f-8fde-4e3e-a00f-73179c1a6117)

**Comment by GenFangirl** [comment]
I went and turned off "Pubic Bot" in the Developer Dashboard, and the bot is now running.  But it only opens when stared from the cmd.  When I close it and attempt to just open it by clicking the executable, I get the "A Java Exception has occurred" error.

**Comment by GamingTimDE** [comment]
Since when did it change that public mode has to be turned off? I ran into the same problem that the bot didn't start after the update. I only found out the error after starting the bot manually with Java -jar. I had always included it in the autostart of the virtual machine.

**Comment by itsCrummy** [comment]
> With just that screenshot it's a bit hard to debug. For anyone still running into this issue, can you share the output of running both `java -version` and `java -jar JMusicBot-0.4.0.jar` on the command line

the issue was because i didnt know i needed Java 11 Lmao - and i dont run it via CMD - but i downloaded Java 11 and it worked so :)

**Comment by TheDjRider** [comment]
I also encountered this bug. If I have the bot with 'Pubic Bot' on JMuiscBot, it crashes after loading in the user list. 

```
openjdk version "11.0.22" 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Debian-1deb11u1, mixed mode, sharing)
```

**Comment by jagrosh** [comment]
Please keep in mind that the issue we are tracking is a java exception occurring. This happens immediately upon double-clicking the jar in a desktop environment.

**Comment by GogoDG** [comment]
I have the same problem. I have java 21 installed and 4.0 jar fails to start.

**Comment by GamingTimDE** [comment]
@GogoDG  public mode has to be turned off in 4.0 idk why they changed. Very disappointed

**Comment by noteventhrice** [comment]
simple fix is to make this return null
https://github.com/jagrosh/MusicBot/blob/b3ffbdba7ddac143250dd566679bc96d78f791e2/src/main/java/com/jagrosh/jmusicbot/utils/OtherUtil.java#L225-L227

idk why its there in the first place but there could be a good reason for it

**Comment by MichailiK** [comment]
From [this commit comment](https://github.com/jagrosh/MusicBot/commit/23c2dfa78e402b5737cbc4b2c8ca9faa0fc74ed3#r139810148):
 
> JMusicBot documentation has always instructed users to mark their bots as private. This update is the first update that actually enforces the instructions. The people complaining about this change are likely the vocal minority.
> 
> - JMusicBot's internals are not optimized for running publicly; there are many design patterns within the code that are designed for ease-of-use or ease-of-maintenance that do not scale well to large numbers of servers.
> 
> - The support server frequently has cases of users asking how to remove their bot from someone's server, and the root issue in most of these cases is that they didn't realize that their bot could be added by anyone.
> 
> - (Hopefully this is not as much of an issue as it has been in the past) People have attempted to pass JMusicBot off as their own bot; some have even attempted to get their bot verified (running a bot that they potentially had zero idea how the internals worked).
> 
> - This change does not prevent the bot owner from adding it to servers.
> 
> - This check only occurs at startup; it is still possible to temporarily make it public if the bot owner isn't able to add it to a server that someone else would be able to.

**Comment by AlmostHuman34** [comment]
> With just that screenshot it's a bit hard to debug. For anyone still running into this issue, can you share the output of running both `java -version` and `java -jar JMusicBot-0.4.0.jar` on the command line

Is there an option to use it now just by double clicking without using cmd? I can open it only via commands you provided.

**Comment by jagrosh** [comment]
I have a feeling that the root cause is multiple java installations, and the install that Windows picks when double-clicking is different from the default one on the Path when using command line. A potential way to help debug this is to make a dummy jar that is compiled with an older version of java that can display the current java version when launched.

One solution that may be worth investigating would be using something like [JSmooth](https://jsmooth.sourceforge.net/) to wrap the jar in an exe file. This might solve some other issues too, like default file types (people accidentally opening the jar in winrar), and possibly even default-filepath issues (where sometimes the 'current directory' doesn't match the jar when double-clicking). If we went this route, we'd need to figure out how to use JSmooth in Github Actions.

**Comment by AlmostHuman34** [comment]
> > With just that screenshot it's a bit hard to debug. For anyone still running into this issue, can you share the output of running both `java -version` and `java -jar JMusicBot-0.4.0.jar` on the command line
> 
> Is there an option to use it now just by double clicking without using cmd? I can open it only via commands you provided.

OK! I found the solution, I uninstalled java 8 and then I installed Java SE Development Kit 11.0.23 from Oracle (skipping their login with bugmenot) and it works, all the versions have no issues with" java exception has occurred"

**Comment by jagrosh** [comment]
Excellent, I suspect that an Adoptium install of Java 11 would have worked as well; I think it was the existence of Java 8 that was causing the problems.

Either way, this seems to be resolved; I'd still like to look into JSmooth but that can be tracked separately. Thanks for the investigation.
